apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-chaos
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cc-chaos
  template:
    metadata:
      labels:
        name: cc-chaos
    spec:
      serviceAccountName: cc-chaos
      containers:
        - name: cc-chaos
          # Replace this with the built image name
          image: skornehl/test-crd:22
          command:
          - cc-chaos
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cc-chaos"
