kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cc-chaos
subjects:
- kind: ServiceAccount
  name: cc-chaos
roleRef:
  kind: Role
  name: cc-chaos
  apiGroup: rbac.authorization.k8s.io
